# Site settings
title: Code Learning
default_author: Aida Albarrán
description: "El blog de una developer con ansias de aprender. Por Aida Albarrán."  # used in site head

# register on google analytics and replace this token
google_analytics: UA-137864641-1
# disque comments are broken if you send http:// along with url, this url is same as the one given on disqus
# Deleting the value would remove it from footer.
disqus_url: alienah.github.io/
disqus_id: https-alienah-github-io
# register on feedburner and replace this url. Deleting the value will remove it from footer.
# feedburner_url: https://feedburner.google.com/fb/a/mailverify?uri=programmer-wannabe&amp;loc=en_US

# footer details. Deleting the value would remove it from footer.
github_username:  Alienah
facebook_username:
email:
stackoverflow_username:
twitter_username : aidaispro
linkedin_username : aidaalbarran
keybase_username :
copyright_name: Aida Albarrán
medium_username: Aida_Pro_
rss : false

# used for portfolio on home page
# collections:
#   - portfolio

# used to estimate reading time
wpm: 150

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888
permalink: /:title

# jekyll-paginate. for paginating blog posts.
paginate: 5
paginate_path: /page:num

# gem dependencies
plugins: [jekyll-paginate, jekyll-feed, jekyll-gist]
